apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vl6ejl9zx-nodejs
  janus-idp.io/tekton: vl6ejl9zx-nodejs
  backstage.io/kubernetes-id: vl6ejl9zx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vl6ejl9zx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
