apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vl6ejl9zx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vl6ejl9zx-nodejs 
  name: vl6ejl9zx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vl6ejl9zx-nodejs 
